// Self-hosted font subsets: downloads from Google Fonts only the glyphs the game actually uses
// (ASCII + Latin-1 + every kana/kanji/symbol found in src/ and index.html) and writes them to
// src/fonts/ together with fonts.css. Run it again after adding new kanji to the UI:
//
//   node scripts/subset_fonts.mjs
//
// Both families are SIL Open Font License 1.1 (Shippori Mincho, Zen Kaku Gothic New).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'src/fonts');
// a modern browser UA makes the CSS API answer with woff2 files
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const FONTS = [
  { family: 'Shippori Mincho', slug: 'shippori-mincho', weights: [700, 800] },
  { family: 'Zen Kaku Gothic New', slug: 'zen-kaku-gothic-new', weights: [500, 700] }
];

// ranges worth asking for: kana, kanji, full-width forms, general punctuation, arrows, shapes
const wanted = (c) =>
  (c >= 0x3000 && c <= 0x30ff) || (c >= 0x3400 && c <= 0x4dbf) || (c >= 0x4e00 && c <= 0x9fff) || (c >= 0xff00 && c <= 0xffef) ||
  (c >= 0x2010 && c <= 0x2027) || (c >= 0x2190 && c <= 0x21ff) || (c >= 0x25a0 && c <= 0x25ff) || c === 0x2713 || c === 0x22ee ||
  (c >= 0x100 && c <= 0x17f);

function scan(file, into) {
  const s = fs.readFileSync(file, 'utf8');
  for (const ch of s) {
    const c = ch.codePointAt(0);
    if (c > 0xff && wanted(c)) into.add(ch);
  }
}
function walk(dir, into) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, into);
    else if (/\.(tsx?|css|html)$/.test(e.name)) scan(p, into);
  }
}

const extra = new Set();
walk(path.join(root, 'src'), extra);
scan(path.join(root, 'index.html'), extra);
let text = '';
for (let c = 0x20; c <= 0x7e; c++) text += String.fromCharCode(c);
for (let c = 0xa0; c <= 0xff; c++) text += String.fromCharCode(c);
text += [...extra].sort().join('');
console.log(`glyphs: ${[...text].length} (${extra.size} beyond Latin-1)`);

fs.mkdirSync(outDir, { recursive: true });
let css = '/* generated by scripts/subset_fonts.mjs - do not edit by hand */\n';
for (const f of FONTS) {
  const api = `https://fonts.googleapis.com/css2?family=${f.family.replace(/ /g, '+')}:wght@${f.weights.join(';')}&text=${encodeURIComponent(text)}&display=swap`;
  const res = await fetch(api, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${f.family}: CSS API ${res.status}`);
  const sheet = await res.text();
  const blocks = [...sheet.matchAll(/@font-face\s*{([^}]*)}/g)].map((m) => m[1]);
  if (blocks.length !== f.weights.length) throw new Error(`${f.family}: expected ${f.weights.length} faces, got ${blocks.length}`);
  for (const b of blocks) {
    const weight = Number(/font-weight:\s*(\d+)/.exec(b)?.[1]);
    const url = /url\((https:[^)]+)\)/.exec(b)?.[1];
    if (!weight || !url) throw new Error(`${f.family}: could not parse a face`);
    const file = `${f.slug}-${weight}.woff2`;
    const data = Buffer.from(await (await fetch(url)).arrayBuffer());
    fs.writeFileSync(path.join(outDir, file), data);
    console.log(`${file}  ${(data.length / 1024).toFixed(1)} KB`);
    css += `@font-face {\n  font-family: '${f.family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('./${file}') format('woff2');\n}\n`;
  }
}
fs.writeFileSync(path.join(outDir, 'fonts.css'), css);
console.log('wrote src/fonts/fonts.css');
